AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'ext/**/*.rb'
  Exclude:
    - '**/*.erb'
    - '**/*.spec'
    - 'acceptance/**/*'
    - 'autotest/**/*'
    - 'ext/packaging/**/*'
    - 'spec/**/*'
    - 'tasks/**/*'
    - 'lib/mcollective/vendor/**/*'

  DisabledByDefault: true


Security/YAMLLoad:
  Enabled: true

# TODO:: Following cops need to be enabled in future
# There are some instances of Eval and Marshal.load being used that 
# need to either rendered safe or marked for exclusion

#Security/Eval:
#  Enabled: true

#Security/MarshalLoad:
#  Enabled: true

