#!/bin/bash

if [ "$1" = "abort-upgrade" ]; then
    exit 0
fi

if [ "$1" = configure ]; then
    gem install stomp
    #invoke-rc.d mcollective start
    exit 0
fi

update-rc.d mcollective defaults 99 >/dev/null

