SET BASEDIR=%~dp0..
SET BASEDIR=%BASEDIR:\bin\..=%

SET SERVER_CONFIG=%BASEDIR%\etc\server.cfg
SET CLIENT_CONFIG=%BASEDIR%\etc\client.cfg

SET MCOLLECTIVED=%BASEDIR%\bin\mcollectived
SET MC_STARTTYPE=manual
REM SET MC_STARTTYPE=auto

SET PATH=%BASEDIR%\bin;%PATH%

SET RUBYLIB=%BASEDIR%\lib;%RUBYLIB%
SET RUBYLIB=%RUBYLIB:\=/%

SET RUBY="ruby"

SET SSL_CERT_FILE=%WINDIR%\system32\ssl\cert.pem
SET SSL_CERT_DIR=%WINDIR%\system32\ssl\certs
